### ISSUE TITLE
Replace MAKE-INSTANCE of PROCESS-OP with ASDF:MAKE-OPERATION

### ISSUE THREAD

**Issue by rpgoldman** [sionescu/iolib#40]
In the forthcoming release of ASDF, using `make-instance` instead of `make-operation` to make an operation class object will cause an error.

This is only done in the groveler, so should be very easy to fix.

Thanks!

**Comment by fare** [comment]
Fixed in https://github.com/sionescu/iolib/pull/41

**Comment by sionescu** [comment]
Fix merged.
