### ISSUE TITLE
Tweak to take advantage of asdf pathname services

### ISSUE THREAD

**Issue by fare** [sionescu/iolib#43]
Some tweaks for the build & test infrastructure:

In tests/streams.lisp, you could have:
```
(defvar *data-dir* (asdf:system-relative-pathname "iolib" "tests/data/"))

(defvar *test-dir*
  (asdf:apply-output-translations
   (asdf:system-relative-pathname "iolib" "tests/test-dir/")))
```

(You could also use (uiop:subpathname (uiop:current-lisp-file) "test-dir/") but that isn't as nice in this context.)

**Comment by sionescu** [comment]
Thanks, fix committed.
