### ISSUE TITLE
Cannot load on SBCL 1.4.1 

### ISSUE THREAD

**Issue by darabi** [sionescu/iolib#51]
I cloned the repo today (commit d3bda105) and tried to load iolib/os with SBCL 1.4.1, which led to

```
; compiling (DEFUN GET-FILE-KIND ...)
debugger invoked on a TYPE-ERROR in thread #<THREAD "main thread" RUNNING {1001B48083}>: The value NIL is not of type SB-C::NODE
```

I have attached a full log: [sbcl-1.4.1-load.log](https://github.com/sionescu/iolib/files/1495627/sbcl-1.4.1-load.log)

Thank you for looking into this.

**Comment by attila-lendvai** [comment]
FTR, this is a bug in SBCL, and it's already fixed.

**Comment by darabi** [comment]
Yes, I tried the current sbcl master which doesn't show this behaviour.
