### ISSUE TITLE
https://common-lisp.net/projects/iolib/ gives HTTP 404

### ISSUE THREAD

**Issue by phoe** [sionescu/iolib#58]
![zrzut ekranu z 2018-09-19 18-03-36](https://user-images.githubusercontent.com/15045546/45765840-57143c80-bc36-11e8-8a28-c8ea623d971d.png)

**Comment by phoe** [comment]
Should be replaced with https://common-lisp.net/project/iolib/ - `s/projects/project/`

**Comment by sionescu** [comment]
Where is that URL present ?

**Comment by phoe** [comment]
Github repo description.
![zrzut ekranu z 2018-09-19 23-06-32](https://user-images.githubusercontent.com/15045546/45781568-aa02e980-bc60-11e8-9b66-0d36c9013cf3.png)

**Comment by sionescu** [comment]
Fixed.
