### ISSUE TITLE
iolib/sockets:lookup-hostname fails on system without /etc/hosts

### ISSUE THREAD

**Issue by dtw-waleee** [sionescu/iolib#64]
On the latest clearlinux the version distributed with quicklisp fails with `Failed to find the WRITE-DATE of /etc/hosts: No such file or directory`.

SBCL-version: `SBCL 2.1.5.38-144526076`
iolib-version: `v0.8.3`

With an empty /etc/hosts it starts to work as expected. ~~I haven't yet checked if the git version of iolib works out-of-the-box without an hosts-file~~ UPDATE: same behaviour with iolib built from master.

**Comment by sionescu** [comment]
Thanks for the report.
