### ISSUE TITLE
Non-helpful errors on non-unix platforms

### ISSUE THREAD

**Issue by Mr-Dispatch** [sionescu/iolib#70]
https://github.com/sionescu/iolib/blob/0001be5721875cc4e3c024560ba956eb0535acd7/iolib.asd#L21

such usage of #+unix (with absence of #-unix alternative - at least an error) like this causes un-even number of arguments / list members on non-unix platforms, leading to puzzling errors on load :-(

```
   (:cffi-grovel-file "ffi-types" :pathname #+unix "ffi-types-unix")
   (:file "conditions")
   (:file "os-conditions" :pathname #+unix "os-conditions-unix")
```

**Comment by sionescu** [comment]
I added an error message that IOlib doesn't work on Windows. For the moment it's all I can do.
