### ISSUE TITLE
remove-fd-handlers errors when there are no fd handlers

### ISSUE THREAD

**Issue by dlowe-net** [sionescu/iolib#73]
I have code that monitors sockets using fd handlers. However, I currently have to check whether or not the fd handler exists (using an unexported function! See #72 ) or risk having a signal:

```
(when (iolib.multiplex::fd-monitored-p *event-base* (socket-os-fd s) :read)
    (remove-fd-handlers *event-base* (socket-os-fd s) :read t))
```
It'd be really nice if I could just call `remove-fd-handlers` blindly.

**Comment by sionescu** [comment]
Your wish is my command.

**Comment by dlowe-net** [comment]
Thanks a bunch!
